# fly.toml app configuration file generated for uneebee on 2023-10-09T14:28:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "uneebee"
primary_region = "iad"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "app.uneebee.com"
  PORT = "8080"

[build.args]
  CDN_URL = "https://cdn.uneebee.com"
  CSP_CONNECT_SRC = "https://*.r2.cloudflarestorage.com"
  PLAUSIBLE_DOMAIN = "app.uneebee.com"
  SENTRY_DSN = "https://a54c82736eef3e6640ff414f83bde12c@o4506042856308736.ingest.sentry.io/4506042856439808"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 1000
